### ISSUE TITLE
Páginas nuevas inexistentes

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-02#13]
Si bien se merodeó la posibilidad de que las páginas de creación, edición y listado de productos pudieran ser entre opcionales y obligatorias, se especificó el hecho de que iban a necesitarlas indispensablemente para el cuarto sprint.
Las páginas actualmente no existen (ni sus respectivas rutas/controladores), por lo que tendrán que sumarlas a la lista de cosas para hacer antes de poder continuar con el resto.

**Comment by Alfredo-Al** [comment]
Hola Aylen, ya se crearon las 2 nuevas paginas de creación y edición, a falta de pequeños detalles que cambiar en la pagina de detalle de producto, ademas se listaran los productos en el home.
