### ISSUE TITLE
Ruta raíz apunta a un error

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-02#14]
Traten de tener cuidado a la hora de hacer el armado de rutas, podría ser algo problemático si lo primero que se ve, al tratar de ingresar a la página, es un Cannot GET (La ruta raíz no tiene una vista asignada, si no que la página principal se encuentra en una ruta /home)

**Comment by VillafaneCristian** [comment]
Consulta... la pagina principal tiene que estar siempre ruteada a "/" ??? Es decir no puedo tener un sistema de ruteo donde la ruta a la pagina principal sea /home o /index siendo que la vista principal es la home.ejs o index.ejs por ejemplo....

**Comment by Alfredo-Al** [comment]
Aylen, ya se soluciono el problema de la ruta raiz con un res.redirect ya si entras a la ruta raiz te aparece el home de nuestra pagina.
