### ISSUE TITLE
Retrospectiva

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-02#15]
Si bien puede parecer algo trivial, sería bueno que traten de implementar la retro entre sus tareas y que el resultado de esta se vea plasmada en algún documento (`retro.md`) donde podamos estar al tanto de como va funcionando su dinámica.

**Comment by Alfredo-Al** [comment]
Ha sido complicado reunirnos a la misma hora ya que todos trabajamos y manejamos husos horarios distintos :(
