### ISSUE TITLE
Mover multer a su propio módulo

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-02#33]
Mejor en su propio módulo ya que no es responsabilidad de la ruta saber cómo se guardan las imágenes

https://github.com/0623CIFSNCN05LAED/grupo-02/blob/4912d251ba62fc70b6df53c6b97938387a6c59a4/src/routes/productRoutes.js#L7-L19

**Comment by Alfredo-Al** [comment]
Listo profe, el multer fue movido a su propio middleware
