### ISSUE TITLE
nombre poco expresivo

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-02#35]
capaz deberían buscar un nombre mejor que archivo... si no a primera vista no se entiende que quiere guardar, es un avatar? un logo? una foto de su perro?

https://github.com/0623CIFSNCN05LAED/grupo-02/blob/4912d251ba62fc70b6df53c6b97938387a6c59a4/src/routes/usersRoutes.js#L24

**Comment by Agus1-acosta** [comment]
buenas luis, si entiendo lo que me dice. realmente se nos paso ahora le vamos a dar un nombre mas especifico y chequear los demas gracias
