### ISSUE TITLE
Public Trello

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-02#5]
No olviden de agregar el trello a su README!! y de dejarlo público

**Comment by VillafaneCristian** [comment]
Se incorpora al archivo README.md el link al tablero de trello. Tambien se adjunta en este mensaje: https://trello.com/w/grupo2fuerzaydisciplina

**Comment by LuiosDyet** [comment]
Gracias, recuerden que es el mismo tablero para todos los sprints, sino corren el riesgo de"olvidarse" lo que les quedó de carry over
