### ISSUE TITLE
nodemon 

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-02#6]
Les sugiero fuertemente, especialmente ahora que vamos a empezar a modificar más los js, que instalen y utilicen un script que tenga nodemon (además del que ya tienen)

https://github.com/0623CIFSNCN05LAED/grupo-02/blob/232aece336d9c667fec8612163f618f82820da12/package.json#L8

**Comment by VillafaneCristian** [comment]
Se instala el paquete "nodemon" y se implementa el script "dev": "nodemon src/app,js"
