### ISSUE TITLE
Ubicación carpeta images

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-02#7]
Tienen dos carpetas images, hay una que quedó adentro de la carpeta CSS que es la que no debería ir y sus imágenes deberían ir en la otra carpeta images que es a donde apunta este link. 

Por otro lado es más flexible agregar cada una de las imágenes como esta hecho en el register más que un carrusel pre-armado. 

https://github.com/0623CIFSNCN05LAED/grupo-02/blob/232aece336d9c667fec8612163f618f82820da12/src/views/home.html#L36

**Comment by VillafaneCristian** [comment]
Se elimina la carpeta "images" que estaba dentro de public\css. Dicha carpeta estaba creada por error en esa ubicacion. La correcta esta alojada dentro de la carpeta "public" que se encuentra en la raiz del proyecto.
