### ISSUE TITLE
Falta archivo normalize

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-02#8]
Vi que normalzaron en el css del home pero si es común a todo, mejor en un archivo común como el normalize, por otro lado lo requieren pero el mismo no existe

https://github.com/0623CIFSNCN05LAED/grupo-02/blob/232aece336d9c667fec8612163f618f82820da12/src/views/home.html#L16

**Comment by VillafaneCristian** [comment]
Se implementa archivo "normalize.css" dentro de la carpeta css que esta en public. Dicho archivo será común a las diferentes vistas.
